ARG PARENT_IMAGE=ubuntu:16.04
FROM $PARENT_IMAGE

RUN echo "source /opt/ros/kinetic/setup.bash" >> "/root/.bashrc"

RUN DEBIAN_FRONTEND=noninteractive apt update && apt -y install \
    vim grep wget \
    ros-kinetic-rqt ros-kinetic-rqt-common-plugins \
    python-catkin-tools \
    python3-pip \
    python-pip \
    software-properties-common apt-transport-https \
    libglfw3-dev libglfw3 \
    gdb \
    && \
    pip3 install python-vagrant gdbgui
